services:
  - type: static
    name: someonesdreamproject-1
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://someonesdreamproject.onrender.com/api
      - key: VITE_STREAM_API_KEY
        sync: false
    autoDeploy: true
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
