[[redirects]]
  from = "/call/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chat/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
